
name: Computer Systems Autograder

on: [push]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run grading script
        run: |
          bash .github/grading/grader.sh
